# The Homepage dashboard: settings.yaml, widgets.yaml and services.yaml.
# Sourced by configure.sh, which loads .env, defines the URL constants
# and the log/ok/skip/die helpers.
#
# settings.yaml and widgets.yaml are generated on every run so the layout
# follows the tiles. To take one over, put "# keep" on its first line and it
# is never touched again. (Homepage writes stock templates into an empty
# config directory on first start; those are replaced too.) services.yaml
# carries API keys and is written fresh every run; every tile has a
# siteMonitor on its internal address, which gives the status dot.

# ---------------------------------------------------------------- Homepage
homepage_keep() { [[ -f "$1" ]] && head -n1 "$1" | grep -qx '# keep'; }
homepage_news_slug() { printf '%s' "$1" | tr '[:upper:]' '[:lower:]' | tr -c 'a-z0-9\n' '-' | sed 's/-\{2,\}/-/g; s/^-//; s/-$//'; }

homepage_settings_yaml() {        # homepage_settings_yaml DIR RECENTLY_ADDED INFRASTRUCTURE
  local dir=$1 recent=$2 infra=$3
  if homepage_keep "$dir/settings.yaml"; then
    skip "settings.yaml (# keep)"
  else
    # The layout only names groups services.yaml will actually carry: without a
    # Plex token there is nothing recently added. Infrastructure is always there
    # - Recyclarr, FlareSolverr and the Docker proxy need no configuration.
    {
      cat <<YAML
# Generated by configure.sh - put "# keep" on this line to make it yours.
title: Media
language: en
headerStyle: clean
hideVersion: true
statusStyle: dot
# No showStats anywhere, on purpose. Homepage keeps no memory of a folded tile
# - the open state is seeded from showStats on every page load - so "open by
# default" means the stats come back on every refresh, and in settings.yaml it
# is worse still: there it forces them open and the fold click cannot close
# them at all. Without it the dashboard stays compact and a status dot expands
# the container it belongs to for as long as you are looking at it.
quicklaunch:
  searchDescriptions: true
  hideInternetSearch: true
  hideVisitURL: true
layout:
  Media:
    style: row
    columns: 2
YAML
      [[ "$recent" == yes ]] && cat <<YAML
  Recently added:
    style: row
    columns: 2
YAML
      cat <<YAML
  Today:
    style: row
    columns: 2
  Downloads:
    style: row
    columns: 2
  Automation:
    style: row
    columns: 3
YAML
      [[ "$infra" == yes ]] && cat <<YAML
  Infrastructure:
    style: row
    # Four, not three: seven tiles over three columns leave one stranded on a
    # row of its own. Over four they fall 4 + 3, and because the four without
    # statistics come first the two rows also end up the same height.
    columns: 4
YAML
    } > "$dir/settings.yaml"
    ok "settings.yaml"
  fi
}

# The dashboard reads each container's state and stats through the socket proxy
# (compose.yml explains what that costs). Tiles name it as "my-docker".
homepage_docker_yaml() {          # homepage_docker_yaml DIR
  local dir=$1
  if homepage_keep "$dir/docker.yaml"; then
    skip "docker.yaml (# keep)"
    return
  fi
  cat > "$dir/docker.yaml" <<YAML
# Generated by configure.sh - put "# keep" on this line to make it yours.
my-docker:
  host: dockerproxy
  port: 2375
YAML
  ok "docker.yaml (container state and stats via dockerproxy)"
}

homepage_widgets_yaml() {         # homepage_widgets_yaml DIR
  local dir=$1
  if homepage_keep "$dir/widgets.yaml"; then
    skip "widgets.yaml (# keep)"
  else
    {
      cat <<YAML
# Generated by configure.sh - put "# keep" on this line to make it yours.
- resources:
    cpu: true
    memory: true
    disk: /data
YAML
      if [[ -n "${WEATHER_LATITUDE:-}" && -n "${WEATHER_LONGITUDE:-}" ]]; then cat <<YAML
- openmeteo:
    label: $(yq "${WEATHER_LABEL:-}")
    latitude: $WEATHER_LATITUDE
    longitude: $WEATHER_LONGITUDE
    timezone: $(yq "${TZ:-UTC}")
    units: metric
    cache: 10
YAML
      fi
      cat <<YAML
- datetime:
    text_size: sm
    locale: $(yq "${UI_LOCALE:-en-US}")
    # Named parts rather than a dateStyle: "za 26 sep, 12:08" keeps the weekday,
    # which is the bit worth a glance, without the year and the spelled-out
    # month that make the full style run the width of the header. A dateStyle of
    # short would fit too, but "26-09-2026, 12:08" reads like a receipt.
    format:
      weekday: short
      day: numeric
      month: short
      hour: 2-digit
      minute: 2-digit
      hour12: $([[ ${UI_TIME_FORMAT:-24h} == 12h ]] && echo true || echo false)
YAML
    } > "$dir/widgets.yaml"
    ok "widgets.yaml${WEATHER_LATITUDE:+ (weather for ${WEATHER_LABEL:-$WEATHER_LATITUDE,$WEATHER_LONGITUDE})}"
  fi
}

homepage_tiles_media() {          # homepage_tiles_media DOMAIN PLEX_TOKEN SEERR_KEY
  local d=$1 plex_token=$2 seerr_key=$3
  cat <<YAML
- Media:
    - Plex:
        href: http://plex.$d/web
        icon: plex.png
        server: my-docker
        container: plex
        siteMonitor: http://$PLEX_INTERNAL_HOST:32400/identity
YAML
  if [[ -n "$plex_token" ]]; then cat <<YAML
        widget:
          type: plex
          url: http://$PLEX_INTERNAL_HOST:32400
          key: $(yq "$plex_token")
YAML
  fi
  cat <<YAML
    - Seerr:
        href: http://seerr.$d
        icon: sh-seerr
        server: my-docker
        container: seerr
        siteMonitor: http://seerr:5055
YAML
  if [[ -n "$seerr_key" ]]; then cat <<YAML
        widget:
          type: seerr
          url: http://seerr:5055
          key: $(yq "$seerr_key")
          fields: ["pending", "processing", "available"]
YAML
  fi
}

homepage_tiles_recently_added() { # homepage_tiles_recently_added DOMAIN PLEX_TOKEN
  local d=$1 plex_token=$2
  # Recently added, straight from Plex's per-library listings (newest first,
  # as JSON). Links open the item
  # in Plex Web.
  if [[ -n "$plex_token" ]]; then
    local machine sections movies_key shows_key
    machine=$(sed -n 's/.*ProcessedMachineIdentifier="\([^"]*\)".*/\1/p' "$PLEX_PREFS")
    sections=$(curl -fsS -m 10 -H "X-Plex-Token: $plex_token" -H 'Accept: application/json' "http://$PLEX_INTERNAL_HOST:32400/library/sections" 2>/dev/null || echo '{}')
    movies_key=$(jq -r '.MediaContainer.Directory[]? | select(.title == "Movies") | .key' <<<"$sections")
    shows_key=$(jq -r '.MediaContainer.Directory[]? | select(.title == "TV Shows") | .key' <<<"$sections")
    if [[ -n "$movies_key" && -n "$shows_key" ]]; then cat <<YAML
- Recently added:
    - Films:
        icon: mdi-movie-open-plus-outline
        href: http://plex.$d/web/index.html#!/media/$machine/com.plexapp.plugins.library?source=$movies_key
        widget:
          type: customapi
          url: $(yq "http://$PLEX_INTERNAL_HOST:32400/library/sections/$movies_key/all?type=1&sort=addedAt:desc&X-Plex-Container-Start=0&X-Plex-Container-Size=8")
          headers:
            Accept: application/json
            X-Plex-Token: $(yq "$plex_token")
          refreshInterval: 300000
          display: dynamic-list
          mappings:
            items: MediaContainer.Metadata
            name: title
            label: year
            limit: 8
            target: $(yq "http://plex.$d/web/index.html#!/server/$machine/details?key=%2Flibrary%2Fmetadata%2F{ratingKey}")
    - Series:
        icon: mdi-television-play
        href: http://plex.$d/web/index.html#!/media/$machine/com.plexapp.plugins.library?source=$shows_key
        widget:
          type: customapi
          url: $(yq "http://$PLEX_INTERNAL_HOST:32400/library/sections/$shows_key/all?type=3&sort=addedAt:desc&X-Plex-Container-Start=0&X-Plex-Container-Size=8")
          headers:
            Accept: application/json
            X-Plex-Token: $(yq "$plex_token")
          refreshInterval: 300000
          display: dynamic-list
          mappings:
            items: MediaContainer.Metadata
            name: parentTitle
            label: title
            limit: 8
            target: $(yq "http://plex.$d/web/index.html#!/server/$machine/details?key=%2Flibrary%2Fmetadata%2F{ratingKey}")
YAML
    fi
  fi
}

homepage_tiles_today() {          # homepage_tiles_today DOMAIN
  local d=$1 entries
  cat <<YAML
- Today:
    - Upcoming series:
        icon: mdi-television-classic
        widget:
          type: calendar
          view: agenda
          maxEvents: 10
          showTime: true
          integrations:
            - type: sonarr
              service_group: Automation
              service_name: Sonarr
              baseUrl: http://sonarr.$d
    - Upcoming films:
        icon: mdi-movie-open-outline
        widget:
          type: calendar
          view: agenda
          maxEvents: 10
          showTime: true
          integrations:
            - type: radarr
              service_group: Automation
              service_name: Radarr
              baseUrl: http://radarr.$d
YAML
  local entry title url
  IFS=';' read -ra entries <<<"${NEWS_FEEDS:-}"
  for entry in "${entries[@]}"; do
    title=${entry%%|*}; url=${entry#*|}
    [[ -n "$title" && "$url" == http* ]] || continue
    url=${url%% *}                    # several sources: the tile links to the first
    cat <<YAML
    - $(yq "$title"):
        icon: mdi-newspaper-variant-outline
        href: $(yq "${url%%/feed*}")
        widget:
          type: customapi
          url: http://localhost:3000/news/$(homepage_news_slug "$title").json
          refreshInterval: 300000
          display: dynamic-list
          mappings:
            items: items
            name: title
            label: published
            format: relativeDate
            limit: 8
            target: "{link}"
YAML
  done
}

homepage_tiles_downloads() {      # homepage_tiles_downloads DOMAIN
  local d=$1
  cat <<YAML
- Downloads:
    - SABnzbd:
        href: http://sabnzbd.$d
        icon: sabnzbd.png
        server: my-docker
        container: sabnzbd
        siteMonitor: http://sabnzbd:8080
        widget:
          type: sabnzbd
          url: http://sabnzbd:8080
          key: $(yq "$SAB_KEY")
    - qBittorrent:
        href: http://qbittorrent.$d
        icon: qbittorrent.png
        server: my-docker
        container: qbittorrent
        siteMonitor: http://$QBT_INTERNAL_HOST:8081
        widget:
          type: qbittorrent
          url: http://$QBT_INTERNAL_HOST:8081
          username: $(yq "$WEBUI_USERNAME")
          password: $(yq "$WEBUI_PASSWORD")
YAML
}

homepage_tiles_automation() {     # homepage_tiles_automation DOMAIN
  local d=$1
  cat <<YAML
- Automation:
    - Sonarr:
        href: http://sonarr.$d
        icon: sonarr.png
        server: my-docker
        container: sonarr
        siteMonitor: http://sonarr:8989
        widget:
          type: sonarr
          url: http://sonarr:8989
          key: $(yq "$(xml_apikey sonarr)")
    - Radarr:
        href: http://radarr.$d
        icon: radarr.png
        server: my-docker
        container: radarr
        siteMonitor: http://radarr:7878
        widget:
          type: radarr
          url: http://radarr:7878
          key: $(yq "$(xml_apikey radarr)")
    - Lidarr:
        href: http://lidarr.$d
        icon: lidarr.png
        server: my-docker
        container: lidarr
        siteMonitor: http://lidarr:8686
        widget:
          type: lidarr
          url: http://lidarr:8686
          key: $(yq "$(xml_apikey lidarr)")
    - Spotweb:
        href: http://spotweb.$d
        icon: mdi-newspaper-variant-outline
        server: my-docker
        container: spotweb
        siteMonitor: $(yq "$SPOTWEB_INTERNAL")
        widget:
          type: customapi
          url: $(yq "$SPOTWEB_INTERNAL/api?t=search&limit=1&o=json&apikey=${SPOTWEB_KEY:-}")
          method: GET
          mappings:
            - field:
                0: _totalrows
              label: spots
              format: number
            - field:
                0: adddate
              label: newest
    - Prowlarr:
        href: http://prowlarr.$d
        icon: prowlarr.png
        server: my-docker
        container: prowlarr
        siteMonitor: $(yq "$PROWLARR_INTERNAL")
        widget:
          type: prowlarr
          url: $(yq "$PROWLARR_INTERNAL")
          key: $(yq "$(xml_apikey prowlarr)")
    - Bazarr:
        href: http://bazarr.$d
        icon: bazarr.png
        server: my-docker
        container: bazarr
        siteMonitor: http://bazarr:6767
        widget:
          type: bazarr
          url: http://bazarr:6767
          key: $(yq "$(sed -n '/^auth:/,/^[^ ]/{s/^ *apikey: *//p}' "$CONFIG_ROOT/bazarr/config/config.yaml" | tr -d "\"'" | head -n1)")
YAML
}

homepage_tiles_infrastructure() {
  echo "- Infrastructure:"
  # No web interface to link to; the tile is there for its container state,
  # which is the only thing there is to know about them.
  cat <<YAML
    - Alerts:
        href: $(yq "http://ntfy.$d/${NTFY_TOPIC:-}")
        icon: ntfy.png
        description: failures worth knowing about
        server: my-docker
        container: ntfy
        siteMonitor: http://ntfy/v1/health
    - Recyclarr:
        icon: mdi-tune-vertical
        description: TRaSH Guides sync
        server: my-docker
        container: recyclarr
    - FlareSolverr:
        icon: mdi-shield-key-outline
        description: indexer challenges
        server: my-docker
        container: flaresolverr
    - Docker proxy:
        icon: mdi-docker
        description: container state for this dashboard
        server: my-docker
        container: dockerproxy
YAML
  # Gluetun's control API answers the public-IP and port routes without a
  # key (its auth.toml, written by setup.sh); /v1/portforward is the
  # post-3.40 route, hence widget version 2.
  cat <<YAML
    - VPN:
        icon: gluetun.png
        server: my-docker
        container: gluetun
        description: torrent traffic exit
        siteMonitor: http://gluetun:8000/v1/publicip/ip
        widget:
          type: gluetun
          url: http://gluetun:8000
          version: 2
          fields: ["public_ip", "country", "port_forwarded"]
YAML
  local ph_url ph_pw ph_label
  for n in "" 2; do
    ph_url=$(eval "printf '%s' \"\${PIHOLE${n}_URL:-}\"")
    [[ -n "$ph_url" ]] || continue
    ph_pw=$(eval "printf '%s' \"\${PIHOLE${n}_PASSWORD:-}\"")
    ph_label=$(eval "printf '%s' \"\${PIHOLE${n}_LABEL:-}\"")
    cat <<YAML
    - $(yq "${ph_label:-Pi-hole}"):
        href: $(yq "$ph_url/admin/")
        icon: pi-hole.png
        # ping, not siteMonitor: siteMonitor is hardcoded to HEAD (Homepage
        # 2.4.0 has no method option), and Pi-hole v6 answers HEAD with 405 plus
        # framing that the dashboard's HTTP parser rejects - HPE_INVALID_CONSTANT,
        # about 40 log errors per ten minutes per tile. Every route behaves that
        # way, so no other path helps. ping probes the host with ICMP instead and
        # reads only the host name from this URL, so it reports the host rather
        # than Pi-hole itself; the widget below is what covers the service.
        ping: $(yq "$ph_url")
        widget:
          type: pihole
          url: $(yq "$ph_url")
          version: 6
          key: $(yq "$ph_pw")
YAML
  done
}

homepage_services_yaml() {        # homepage_services_yaml DIR DOMAIN PLEX_TOKEN SEERR_KEY
  local dir=$1 d=$2 plex_token=$3 seerr_key=$4
  {
    echo "# Generated by configure.sh - edits are overwritten on the next run."
    homepage_tiles_media "$d" "$plex_token" "$seerr_key"
    homepage_tiles_recently_added "$d" "$plex_token"
    homepage_tiles_today "$d"
    homepage_tiles_downloads "$d"
    homepage_tiles_automation "$d"
    homepage_tiles_infrastructure
  } > "$dir/services.yaml"
  chmod 600 "$dir/services.yaml"
  ok "services.yaml (API keys inside, mode 600)"
}

homepage_refresh_news() {         # homepage_refresh_news DIR
  local dir=$1 entries
  if [[ -w "$dir/news" || ( ! -e "$dir/news" && -w "$dir" ) ]]; then
    ./news.sh >/dev/null && ok "headlines fetched for: $(tr ';' '\n' <<<"$NEWS_FEEDS" | cut -d'|' -f1 | paste -sd, - | sed 's/,/, /g') (news.sh)"
    # Homepage lists its static files once at start; a feed file that is new
    # since then is 404 until the container restarts (updates to an existing
    # file are served as they are).
    local entry missing=0
    IFS=';' read -ra entries <<<"$NEWS_FEEDS"
    for entry in "${entries[@]}"; do
      docker compose exec -T homepage wget -q -O /dev/null -T 5 "http://localhost:3000/news/$(homepage_news_slug "${entry%%|*}").json" 2>/dev/null || missing=1
    done
    if (( missing )); then
      docker compose restart homepage >/dev/null 2>&1
      ok "Homepage restarted to pick up new feed files"
    fi
    systemctl --user is-enabled media-stack-news.timer >/dev/null 2>&1 || echo "        (install the refresh timer: ./news.sh install)"
  else
    echo "   WARN $dir/news is not writable (created by Docker as root?): sudo chown $USER $dir/news"
  fi
}

configure_homepage() {
  log "Homepage dashboard"
  local dir="$CONFIG_ROOT/homepage" plex_token seerr_key
  plex_token=$(plex_token)
  seerr_key=$(jq -r 'select(.public.initialized == true) | .main.apiKey // empty' "$CONFIG_ROOT/seerr/settings.json" 2>/dev/null || true)

  local recent=no
  [[ -n "$plex_token" ]] && recent=yes
  homepage_settings_yaml "$dir" "$recent" yes
  homepage_widgets_yaml "$dir"
  homepage_docker_yaml "$dir"
  [[ -f "$dir/bookmarks.yaml" ]] || : > "$dir/bookmarks.yaml"
  homepage_services_yaml "$dir" "$SITE_DOMAIN" "$plex_token" "$seerr_key"
  [[ -n "$plex_token" ]] || echo "        (Plex tile gets its widget once the server is claimed)"
  [[ -n "$seerr_key" ]] || echo "        (Seerr tile gets its widget once Seerr's setup is completed)"
  [[ -z "${NEWS_FEEDS:-}" ]] || homepage_refresh_news "$dir"
  if (( LOGIN_CHANGED )); then
    # qBittorrent may have banned Homepage's IP for stale-login attempts made
    # before the stop above took effect; a restart clears the in-memory ban.
    docker compose restart qbittorrent >/dev/null 2>&1
    docker compose start homepage >/dev/null 2>&1
    ok "Homepage restarted with the new login"
  fi
  # The dashboard is a statically generated page: writing the YAML changes
  # nothing a browser can see until the page is rebuilt, and a plain container
  # restart keeps the cached one. Homepage's own endpoint does the rebuild,
  # which is why the tiles show a setting the moment this script sets it.
  if curl -fsS -o /dev/null -m 15 "http://localhost:3000/api/revalidate" 2>/dev/null; then
    ok "dashboard page rebuilt"
  else
    echo "        (could not reach Homepage to rebuild its page; it refreshes by itself within the hour)"
  fi
}
