# The Homepage dashboard: settings.yaml, widgets.yaml and services.yaml.
# Sourced by configure.sh, which loads .env, defines the URL constants
# and the log/ok/skip/die helpers.
#
# settings.yaml and widgets.yaml are generated on every run so the layout
# follows the tiles. To take one over, put "# keep" on its first line and it
# is never touched again. (Homepage writes stock templates into an empty
# config directory on first start; those are replaced too.) services.yaml
# carries API keys and is written fresh every run; every tile has a
# siteMonitor on its internal address, which gives the status dot.

# ---------------------------------------------------------------- Homepage
# "/* keep */" as well as "# keep", because custom.css is CSS and a bare
# "# keep" on line 1 is a parse error that would eat the first rule after it.
homepage_keep() { [[ -f "$1" ]] && head -n1 "$1" | grep -qxE '# keep|/\* keep \*/'; }
homepage_news_slug() { printf '%s' "$1" | tr '[:upper:]' '[:lower:]' | tr -c 'a-z0-9\n' '-' | sed 's/-\{2,\}/-/g; s/^-//; s/-$//'; }

# Which resource block the archive disk is, counting from 1. The widget renders
# cpu, then memory, then the disks in the order widgets.yaml lists them, so the
# number depends on what that file turned on - which is why it is read back out
# of the generated file rather than written down twice and left to drift.
homepage_archive_resource_index() {   # homepage_archive_resource_index DIR
  local f=$1/widgets.yaml
  [[ -f "$f" ]] || return 1
  awk '
    /^- resources:/ { inres = 1; next }
    /^- /           { inres = 0 }
    !inres          { next }
    /cpu: true/     { n++ }
    /memory: true/  { n++ }
    /^ *disk: *\//  { n++; if ($0 ~ /\/data\/archive\/media$/) { print n; found = 1; exit } }
    /^ *- *\//      { n++; if ($0 ~ /\/data\/archive\/media$/) { print n; found = 1; exit } }
    END             { if (!found) exit 1 }
  ' "$f"
}

homepage_custom_css() {           # homepage_custom_css DIR
  local dir=$1 cloud nth
  if homepage_keep "$dir/custom.css"; then
    skip "custom.css (kept)"
    return 0
  fi
  nth=$(homepage_archive_resource_index "$dir" 2>/dev/null) || nth=""
  # A Feather-style cloud, stroked, used as a mask rather than as an image: the
  # mask takes the alpha and background-color paints it, so the glyph follows
  # the theme instead of being a fixed colour.
  cloud="data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 24 24' fill='none' stroke='%23000' stroke-width='2' stroke-linecap='round' stroke-linejoin='round'%3E%3Cpath d='M18 10h-1.26A8 8 0 1 0 9 20h9a5 5 0 0 0 0-10z'/%3E%3C/svg%3E"
  {
    echo "/* Generated by configure.sh - see the next line to take it over. */"
    echo "/* keep   <- make that line 1, comment markers and all, and this file is yours. */"
    if archive_enabled && [[ -n "$nth" ]]; then
      cat <<CSS

/* The archive is the last disk in the resources widget. That widget takes no
   icon: key of its own - icons belong to services, which is how the Archive
   tile gets its mdi-cloud-lock-outline - so the drive glyph is masked into a
   cloud here instead. The <svg> itself is masked rather than replaced, which
   keeps its w-5 h-5 sizing and its text-theme classes, so currentColor goes on
   following light and dark. Only written while the tier is on: with it off the
   last disk is /data, and a cloud over the local disk would be a lie. */
#widgets-wrap .information-widget-resource:nth-child($nth) .resource-icon > * { display: none; }
#widgets-wrap .information-widget-resource:nth-child($nth) .resource-icon {
  background-color: currentColor;
  -webkit-mask: url("$cloud") center / contain no-repeat;
          mask: url("$cloud") center / contain no-repeat;
}
CSS
    fi
  } > "$dir/custom.css"
  if archive_enabled && [[ -n "$nth" ]]; then
    ok "custom.css (cloud glyph on resource $nth, the archive disk)"
  elif archive_enabled; then
    ok "custom.css (no cloud: could not place the archive disk in widgets.yaml)"
  else
    ok "custom.css"
  fi
}

# Columns that leave no tile alone on the last row. Three where it divides,
# four or two where it does not: seven tiles over three columns strand one,
# which is the arithmetic Infrastructure below already carries by hand.
homepage_columns() {              # homepage_columns TILE_COUNT
  local n=${1:-0} c
  (( n > 0 )) || { printf 3; return 0; }
  (( n <= 3 )) && { printf '%d' "$n"; return 0; }
  for c in 3 4 2; do (( n % c != 1 )) && { printf '%d' "$c"; return 0; }; done
  printf 3
}

# How many headline tiles NEWS_FEEDS will actually produce - the same test the
# tile loop applies, so the column count matches what gets rendered.
homepage_news_count() {
  local entries entry title url n=0
  IFS=';' read -ra entries <<<"${NEWS_FEEDS:-}"
  for entry in "${entries[@]}"; do
    title=${entry%%|*}; url=${entry#*|}
    [[ -n "$title" && "$url" == http* ]] && n=$(( n + 1 ))
  done
  printf '%d' "$n"
}

homepage_settings_yaml() {        # homepage_settings_yaml DIR RECENTLY_ADDED INFRASTRUCTURE
  local dir=$1 recent=$2 infra=$3
  if homepage_keep "$dir/settings.yaml"; then
    skip "settings.yaml (# keep)"
  else
    # The layout only names groups services.yaml will actually carry: without a
    # Plex token there is nothing recently added. Infrastructure is always there
    # - Recyclarr, FlareSolverr and the Docker proxy need no configuration.
    {
      cat <<YAML
# Generated by configure.sh - put "# keep" on this line to make it yours.
title: Media
language: en
headerStyle: clean
hideVersion: true
statusStyle: dot
# No showStats anywhere, on purpose. Homepage keeps no memory of a folded tile
# - the open state is seeded from showStats on every page load - so "open by
# default" means the stats come back on every refresh, and in settings.yaml it
# is worse still: there it forces them open and the fold click cannot close
# them at all. Without it the dashboard stays compact and a status dot expands
# the container it belongs to for as long as you are looking at it.
quicklaunch:
  searchDescriptions: true
  hideInternetSearch: true
  hideVisitURL: true
layout:
  Media:
    style: row
    columns: 2
YAML
      # Three: Films, Series and Music where there is a music library, two where
      # there is not, and neither leaves a tile stranded on a row of its own.
      [[ "$recent" == yes ]] && cat <<YAML
  Recently added:
    style: row
    columns: 3
YAML
      cat <<YAML
  Today:
    style: row
    columns: $(homepage_columns $(( 3 + $(homepage_news_count) )))
  Downloads:
    style: row
    columns: 2
  Automation:
    style: row
    columns: 3
YAML
      [[ "$infra" == yes ]] && cat <<YAML
  Infrastructure:
    style: row
    # Four, not three: seven tiles over three columns leave one stranded on a
    # row of its own. Over four they fall 4 + 3, and because the four without
    # statistics come first the two rows also end up the same height.
    columns: 4
YAML
    } > "$dir/settings.yaml"
    ok "settings.yaml"
  fi
}

# The dashboard reads each container's state and stats through the socket proxy
# (compose.yml explains what that costs). Tiles name it as "my-docker".
homepage_docker_yaml() {          # homepage_docker_yaml DIR
  local dir=$1
  if homepage_keep "$dir/docker.yaml"; then
    skip "docker.yaml (# keep)"
    return
  fi
  cat > "$dir/docker.yaml" <<YAML
# Generated by configure.sh - put "# keep" on this line to make it yours.
my-docker:
  host: dockerproxy
  port: 2375
YAML
  ok "docker.yaml (container state and stats via dockerproxy)"
}

homepage_widgets_yaml() {         # homepage_widgets_yaml DIR
  local dir=$1
  if homepage_keep "$dir/widgets.yaml"; then
    skip "widgets.yaml (# keep)"
  else
    {
      # The archive gets its own figure only when the tier is on. It is where
      # things go when /data fills, so the one number that matters during a
      # mover run - is there anywhere left to move to - is invisible without it.
      # archive_enabled, not just the rclone service: without a remote in
      # rclone.conf nothing mounts, and /data/archive/media is then a plain
      # directory that would report the local disk a second time. The path is
        # the mount itself, not data/archive above it: since the union that is an
        # ordinary directory, and watching it gave the local disk two tiles, one
        # of them wearing a cloud.
      if archive_enabled; then
        # One group, two disks, no labels: the second entry is the archive and
        # custom.css swaps its drive glyph for a cloud, which says the same
        # thing without a caption. The widget takes no icon: key of its own -
        # that belongs to services, which is how the Archive tile further down
        # gets its mdi-cloud-lock-outline - so the icon is styled, not set.
        cat <<YAML
# Generated by configure.sh - put "# keep" on this line to make it yours.
- resources:
    cpu: true
    memory: true
    disk:
      - /data
      - /data/archive/media
YAML
      else
        cat <<YAML
# Generated by configure.sh - put "# keep" on this line to make it yours.
- resources:
    cpu: true
    memory: true
    disk: /data
YAML
      fi
      if [[ -n "${WEATHER_LATITUDE:-}" && -n "${WEATHER_LONGITUDE:-}" ]]; then cat <<YAML
- openmeteo:
    label: $(yq "${WEATHER_LABEL:-}")
    latitude: $WEATHER_LATITUDE
    longitude: $WEATHER_LONGITUDE
    timezone: $(yq "${TZ:-UTC}")
    units: metric
    cache: 10
YAML
      fi
      cat <<YAML
- datetime:
    text_size: sm
    locale: $(yq "${UI_LOCALE:-en-US}")
    # Named parts rather than a dateStyle: "za 26 sep, 12:08" keeps the weekday,
    # which is the bit worth a glance, without the year and the spelled-out
    # month that make the full style run the width of the header. A dateStyle of
    # short would fit too, but "26-09-2026, 12:08" reads like a receipt.
    format:
      weekday: short
      day: numeric
      month: short
      hour: 2-digit
      minute: 2-digit
      hour12: $([[ ${UI_TIME_FORMAT:-24h} == 12h ]] && echo true || echo false)
YAML
    } > "$dir/widgets.yaml"
    ok "widgets.yaml${WEATHER_LATITUDE:+ (weather for ${WEATHER_LABEL:-$WEATHER_LATITUDE,$WEATHER_LONGITUDE})}"
  fi
}

homepage_tiles_media() {          # homepage_tiles_media DOMAIN PLEX_TOKEN SEERR_KEY
  local d=$1 plex_token=$2 seerr_key=$3
  cat <<YAML
- Media:
    - Plex:
        href: http://plex.$d/web
        icon: plex.png
        server: my-docker
        container: plex
        siteMonitor: http://$PLEX_INTERNAL_HOST:32400/identity
YAML
  if [[ -n "$plex_token" ]]; then cat <<YAML
        widget:
          type: plex
          url: http://$PLEX_INTERNAL_HOST:32400
          key: $(yq "$plex_token")
YAML
  fi
  cat <<YAML
    - Seerr:
        href: http://seerr.$d
        icon: sh-seerr
        server: my-docker
        container: seerr
        siteMonitor: http://seerr:5055
YAML
  if [[ -n "$seerr_key" ]]; then cat <<YAML
        widget:
          type: seerr
          url: http://seerr:5055
          key: $(yq "$seerr_key")
          fields: ["pending", "processing", "available"]
YAML
  fi
}

homepage_tiles_recently_added() { # homepage_tiles_recently_added DOMAIN PLEX_TOKEN
  local d=$1 plex_token=$2
  # Recently added, straight from Plex's per-library listings (newest first,
  # as JSON). Links open the item
  # in Plex Web.
  if [[ -n "$plex_token" ]]; then
    local machine sections movies_key shows_key music_key
    machine=$(sed -n 's/.*ProcessedMachineIdentifier="\([^"]*\)".*/\1/p' "$PLEX_PREFS")
    sections=$(curl -fsS -m 10 -H "X-Plex-Token: $plex_token" -H 'Accept: application/json' "http://$PLEX_INTERNAL_HOST:32400/library/sections" 2>/dev/null || echo '{}')
    movies_key=$(jq -r '.MediaContainer.Directory[]? | select(.title == "Movies") | .key' <<<"$sections")
    shows_key=$(jq -r '.MediaContainer.Directory[]? | select(.title == "TV Shows") | .key' <<<"$sections")
    # By type, not by title: the films and series libraries are named by this
    # stack, but a music library may be called anything and there may be none.
    music_key=$(jq -r 'first(.MediaContainer.Directory[]? | select(.type == "artist") | .key) // empty' <<<"$sections")
    if [[ -n "$movies_key" && -n "$shows_key" ]]; then cat <<YAML
- Recently added:
    - Films:
        icon: mdi-movie-open-plus-outline
        href: http://plex.$d/web/index.html#!/media/$machine/com.plexapp.plugins.library?source=$movies_key
        widget:
          type: customapi
          url: $(yq "http://$PLEX_INTERNAL_HOST:32400/library/sections/$movies_key/all?type=1&sort=addedAt:desc&X-Plex-Container-Start=0&X-Plex-Container-Size=8")
          headers:
            Accept: application/json
            X-Plex-Token: $(yq "$plex_token")
          refreshInterval: 300000
          display: dynamic-list
          mappings:
            items: MediaContainer.Metadata
            name: title
            label: year
            limit: 8
            target: $(yq "http://plex.$d/web/index.html#!/server/$machine/details?key=%2Flibrary%2Fmetadata%2F{ratingKey}")
    - Series:
        icon: mdi-television-play
        href: http://plex.$d/web/index.html#!/media/$machine/com.plexapp.plugins.library?source=$shows_key
        widget:
          type: customapi
          url: $(yq "http://$PLEX_INTERNAL_HOST:32400/library/sections/$shows_key/all?type=3&sort=addedAt:desc&X-Plex-Container-Start=0&X-Plex-Container-Size=8")
          headers:
            Accept: application/json
            X-Plex-Token: $(yq "$plex_token")
          refreshInterval: 300000
          display: dynamic-list
          mappings:
            items: MediaContainer.Metadata
            name: parentTitle
            label: title
            limit: 8
            target: $(yq "http://plex.$d/web/index.html#!/server/$machine/details?key=%2Flibrary%2Fmetadata%2F{ratingKey}")
YAML
      # Albums rather than tracks (type 9, not 10), or one import fills the tile
      # with its own track listing. parentTitle is the artist, title the album -
      # the same shape as Series, where it is the show and the season.
      if [[ -n "$music_key" ]]; then cat <<YAML
    - Music:
        icon: mdi-music-note-plus
        href: http://plex.$d/web/index.html#!/media/$machine/com.plexapp.plugins.library?source=$music_key
        widget:
          type: customapi
          url: $(yq "http://$PLEX_INTERNAL_HOST:32400/library/sections/$music_key/all?type=9&sort=addedAt:desc&X-Plex-Container-Start=0&X-Plex-Container-Size=8")
          headers:
            Accept: application/json
            X-Plex-Token: $(yq "$plex_token")
          refreshInterval: 300000
          display: dynamic-list
          mappings:
            items: MediaContainer.Metadata
            name: parentTitle
            label: title
            limit: 8
            target: $(yq "http://plex.$d/web/index.html#!/server/$machine/details?key=%2Flibrary%2Fmetadata%2F{ratingKey}")
YAML
      fi
    fi
  fi
}

homepage_tiles_today() {          # homepage_tiles_today DOMAIN
  local d=$1 entries
  cat <<YAML
- Today:
    - Upcoming series:
        icon: mdi-television-classic
        widget:
          type: calendar
          view: agenda
          maxEvents: 10
          showTime: true
          integrations:
            - type: sonarr
              service_group: Automation
              service_name: Sonarr
              baseUrl: http://sonarr.$d
    - Upcoming films:
        icon: mdi-movie-open-outline
        widget:
          type: calendar
          view: agenda
          maxEvents: 10
          showTime: true
          integrations:
            - type: radarr
              service_group: Automation
              service_name: Radarr
              baseUrl: http://radarr.$d
    - Upcoming music:
        icon: mdi-music-note-plus
        widget:
          type: calendar
          view: agenda
          maxEvents: 10
          showTime: true
          integrations:
            - type: lidarr
              service_group: Automation
              service_name: Lidarr
              baseUrl: http://lidarr.$d
YAML
  local entry title url
  IFS=';' read -ra entries <<<"${NEWS_FEEDS:-}"
  for entry in "${entries[@]}"; do
    title=${entry%%|*}; url=${entry#*|}
    [[ -n "$title" && "$url" == http* ]] || continue
    url=${url%% *}                    # several sources: the tile links to the first
    cat <<YAML
    - $(yq "$title"):
        icon: mdi-newspaper-variant-outline
        href: $(yq "${url%%/feed*}")
        widget:
          type: customapi
          url: http://localhost:3000/news/$(homepage_news_slug "$title").json
          refreshInterval: 300000
          display: dynamic-list
          mappings:
            items: items
            name: title
            label: published
            format: relativeDate
            limit: 8
            target: "{link}"
YAML
  done
}

homepage_tiles_downloads() {      # homepage_tiles_downloads DOMAIN
  local d=$1
  cat <<YAML
- Downloads:
    - SABnzbd:
        href: http://sabnzbd.$d
        icon: sabnzbd.png
        server: my-docker
        container: sabnzbd
        siteMonitor: http://sabnzbd:8080
        widget:
          type: sabnzbd
          url: http://sabnzbd:8080
          key: $(yq "$SAB_KEY")
    - qBittorrent:
        href: http://qbittorrent.$d
        icon: qbittorrent.png
        server: my-docker
        container: qbittorrent
        siteMonitor: http://$QBT_INTERNAL_HOST:8081
        widget:
          type: qbittorrent
          url: http://$QBT_INTERNAL_HOST:8081
          username: $(yq "$WEBUI_USERNAME")
          password: $(yq "$WEBUI_PASSWORD")
YAML
}

homepage_tiles_automation() {     # homepage_tiles_automation DOMAIN
  local d=$1
  cat <<YAML
- Automation:
    - Sonarr:
        href: http://sonarr.$d
        icon: sonarr.png
        server: my-docker
        container: sonarr
        siteMonitor: http://sonarr:8989
        widget:
          type: sonarr
          url: http://sonarr:8989
          key: $(yq "$(xml_apikey sonarr)")
    - Radarr:
        href: http://radarr.$d
        icon: radarr.png
        server: my-docker
        container: radarr
        siteMonitor: http://radarr:7878
        widget:
          type: radarr
          url: http://radarr:7878
          key: $(yq "$(xml_apikey radarr)")
    - Lidarr:
        href: http://lidarr.$d
        icon: lidarr.png
        server: my-docker
        container: lidarr
        siteMonitor: http://lidarr:8686
        widget:
          type: lidarr
          url: http://lidarr:8686
          key: $(yq "$(xml_apikey lidarr)")
    - Spotweb:
        href: http://spotweb.$d
        icon: mdi-newspaper-variant-outline
        server: my-docker
        container: spotweb
        siteMonitor: $(yq "$SPOTWEB_INTERNAL")
        widget:
          type: customapi
          url: $(yq "$SPOTWEB_INTERNAL/api?t=search&limit=1&o=json&apikey=${SPOTWEB_KEY:-}")
          method: GET
          mappings:
            - field:
                0: _totalrows
              label: spots
              format: number
            - field:
                0: adddate
              label: newest
    - Prowlarr:
        href: http://prowlarr.$d
        icon: prowlarr.png
        server: my-docker
        container: prowlarr
        siteMonitor: $(yq "$PROWLARR_INTERNAL")
        widget:
          type: prowlarr
          url: $(yq "$PROWLARR_INTERNAL")
          key: $(yq "$(xml_apikey prowlarr)")
    - Bazarr:
        href: http://bazarr.$d
        icon: bazarr.png
        server: my-docker
        container: bazarr
        siteMonitor: http://bazarr:6767
        widget:
          type: bazarr
          url: http://bazarr:6767
          key: $(yq "$(sed -n '/^auth:/,/^[^ ]/{s/^ *apikey: *//p}' "$CONFIG_ROOT/bazarr/config/config.yaml" | tr -d "\"'" | head -n1)")
YAML
}

homepage_tiles_infrastructure() {
  echo "- Infrastructure:"
  # No web interface to link to; the tile is there for its container state,
  # which is the only thing there is to know about them.
  cat <<YAML
    - Alerts:
        href: $(yq "http://ntfy.$d/${NTFY_TOPIC:-}")
        icon: ntfy.png
        description: failures worth knowing about
        server: my-docker
        container: ntfy
        siteMonitor: http://ntfy/v1/health
    - Recyclarr:
        icon: mdi-tune-vertical
        description: TRaSH Guides sync
        server: my-docker
        container: recyclarr
    - FlareSolverr:
        icon: mdi-shield-key-outline
        description: indexer challenges
        server: my-docker
        container: flaresolverr
    - Docker proxy:
        icon: mdi-docker
        description: container state for this dashboard
        server: my-docker
        container: dockerproxy
YAML
  # Only when the archive tier is switched on: with COMPOSE_PROFILES empty there
  # is no rclone container, and a tile for a container that does not exist reads
  # as something broken rather than something not in use.
  #
  # The widget reads rclone's own rc API, which compose binds to 0.0.0.0 on the
  # private network with RCLONE_RC_USER/PASS. Those are container arguments, so
  # a container that is still running with the old --rc-addr 127.0.0.1 refuses
  # the connection and the tile shows no figures until rclone next restarts.
  # That is deliberate: recreating it while the union is assembled leaves a dead
  # FUSE endpoint only root can clear (AGENTS.md), so this waits for a restart
  # that happens anyway rather than forcing one.
  if docker compose config --services 2>/dev/null | grep -qx rclone; then
    cat <<YAML
    - Archive:
        icon: mdi-cloud-lock-outline
        description: what did not fit, still playable
        server: my-docker
        container: rclone
        # One widget, so one row. The upload backlog lives on vfs/stats and the
        # rate on core/stats, and a widget is one request - two endpoints would be
        # two rows.
        #
        # Not core/stats.speed: that is bytes/elapsedTime over the whole process
        # life and counts both directions, so it read 57 MB/s on a day when nothing
        # uploaded at all and every byte was Bazarr reading the archive back down.
        # transferring.0.speed is the file actually in flight. bitrate formatting
        # with scale 8 because rclone reports bytes/s and Mbps is what the rest of
        # the stack is configured in.
        widget:
          type: customapi
          url: http://rclone:5572/core/stats
          method: POST
          username: $(yq "$WEBUI_USERNAME")
          password: $(yq "$WEBUI_PASSWORD")
          refreshInterval: 10000
          # list, not the default block: block stacks the value above the label,
          # so a field reads as two lines.
          display: list
          mappings:
            # rclone reports bytes/s. scale converts to Mbit/s (x8 for bits, /1e6
            # for mega) and the unit is spelled out, because Homepage's own bitrate
            # format renders "b/s" at low values and that reads as bytes.
            #
            # This is the file actually in flight, not core/stats.speed - that is
            # bytes/elapsedTime over the whole process life and counts both
            # directions, so it read 57 MB/s on a day when nothing uploaded at all.
            #
            # One field, because the number worth pairing it with - how many files
            # are waiting to go up - is on vfs/stats, and a widget is one request.
            # core/stats.transfers was tried and dropped: it counts completed
            # transfers in both directions since the container started, so it resets
            # on a restart and answers no question anyone asks.
            - field: transferring.0.speed
              label: uploading
              scale: 0.000008
              format: number
              suffix: Mbit/s
YAML
  fi
  # Gluetun's control API answers the public-IP and port routes without a
  # key (its auth.toml, written by setup.sh); /v1/portforward is the
  # post-3.40 route, hence widget version 2.
  cat <<YAML
    - VPN:
        icon: gluetun.png
        server: my-docker
        container: gluetun
        description: torrent traffic exit
        siteMonitor: http://gluetun:8000/v1/publicip/ip
        widget:
          type: gluetun
          url: http://gluetun:8000
          version: 2
          fields: ["public_ip", "country", "port_forwarded"]
YAML
  local ph_url ph_pw ph_label
  for n in "" 2; do
    ph_url=$(eval "printf '%s' \"\${PIHOLE${n}_URL:-}\"")
    [[ -n "$ph_url" ]] || continue
    ph_pw=$(eval "printf '%s' \"\${PIHOLE${n}_PASSWORD:-}\"")
    ph_label=$(eval "printf '%s' \"\${PIHOLE${n}_LABEL:-}\"")
    cat <<YAML
    - $(yq "${ph_label:-Pi-hole}"):
        href: $(yq "$ph_url/admin/")
        icon: pi-hole.png
        # ping, not siteMonitor: siteMonitor is hardcoded to HEAD (Homepage
        # 2.4.0 has no method option), and Pi-hole v6 answers HEAD with 405 plus
        # framing that the dashboard's HTTP parser rejects - HPE_INVALID_CONSTANT,
        # about 40 log errors per ten minutes per tile. Every route behaves that
        # way, so no other path helps. ping probes the host with ICMP instead and
        # reads only the host name from this URL, so it reports the host rather
        # than Pi-hole itself; the widget below is what covers the service.
        ping: $(yq "$ph_url")
        widget:
          type: pihole
          url: $(yq "$ph_url")
          version: 6
          key: $(yq "$ph_pw")
YAML
  done
}

homepage_services_yaml() {        # homepage_services_yaml DIR DOMAIN PLEX_TOKEN SEERR_KEY
  local dir=$1 d=$2 plex_token=$3 seerr_key=$4
  {
    echo "# Generated by configure.sh - edits are overwritten on the next run."
    homepage_tiles_media "$d" "$plex_token" "$seerr_key"
    homepage_tiles_recently_added "$d" "$plex_token"
    homepage_tiles_today "$d"
    homepage_tiles_downloads "$d"
    homepage_tiles_automation "$d"
    homepage_tiles_infrastructure
  } > "$dir/services.yaml"
  chmod 600 "$dir/services.yaml"
  ok "services.yaml (API keys inside, mode 600)"
}

homepage_refresh_news() {         # homepage_refresh_news DIR
  local dir=$1 entries
  if [[ -w "$dir/news" || ( ! -e "$dir/news" && -w "$dir" ) ]]; then
    ./news.sh >/dev/null && ok "headlines fetched for: $(tr ';' '\n' <<<"$NEWS_FEEDS" | cut -d'|' -f1 | paste -sd, - | sed 's/,/, /g') (news.sh)"
    # Homepage lists its static files once at start; a feed file that is new
    # since then is 404 until the container restarts (updates to an existing
    # file are served as they are).
    local entry missing=0
    IFS=';' read -ra entries <<<"$NEWS_FEEDS"
    for entry in "${entries[@]}"; do
      docker compose exec -T homepage wget -q -O /dev/null -T 5 "http://localhost:3000/news/$(homepage_news_slug "${entry%%|*}").json" 2>/dev/null || missing=1
    done
    if (( missing )); then
      docker compose restart homepage >/dev/null 2>&1
      ok "Homepage restarted to pick up new feed files"
    fi
    systemctl --user is-enabled media-stack-news.timer >/dev/null 2>&1 || echo "        (install the refresh timer: ./news.sh install)"
  else
    echo "   WARN $dir/news is not writable (created by Docker as root?): sudo chown $USER $dir/news"
  fi
}

configure_homepage() {
  log "Homepage dashboard"
  local dir="$CONFIG_ROOT/homepage" plex_token seerr_key
  plex_token=$(plex_token)
  seerr_key=$(jq -r 'select(.public.initialized == true) | .main.apiKey // empty' "$CONFIG_ROOT/seerr/settings.json" 2>/dev/null || true)

  local recent=no
  [[ -n "$plex_token" ]] && recent=yes
  homepage_settings_yaml "$dir" "$recent" yes
  homepage_widgets_yaml "$dir"
  # After widgets.yaml, never before: custom.css pins the archive disk by its
  # position in that file and counts it back out of the file itself, so writing
  # the two in the other order would style whatever the previous run listed.
  homepage_custom_css "$dir"
  homepage_docker_yaml "$dir"
  [[ -f "$dir/bookmarks.yaml" ]] || : > "$dir/bookmarks.yaml"
  homepage_services_yaml "$dir" "$SITE_DOMAIN" "$plex_token" "$seerr_key"
  [[ -n "$plex_token" ]] || echo "        (Plex tile gets its widget once the server is claimed)"
  [[ -n "$seerr_key" ]] || echo "        (Seerr tile gets its widget once Seerr's setup is completed)"
  [[ -z "${NEWS_FEEDS:-}" ]] || homepage_refresh_news "$dir"
  if (( LOGIN_CHANGED )); then
    # qBittorrent may have banned Homepage's IP for stale-login attempts made
    # before the stop above took effect; a restart clears the in-memory ban.
    docker compose restart qbittorrent >/dev/null 2>&1
    docker compose start homepage >/dev/null 2>&1
    ok "Homepage restarted with the new login"
  fi
  # The dashboard is a statically generated page: writing the YAML changes
  # nothing a browser can see until the page is rebuilt, and a plain container
  # restart keeps the cached one. Homepage's own endpoint does the rebuild,
  # which is why the tiles show a setting the moment this script sets it.
  if curl -fsS -o /dev/null -m 15 "http://localhost:3000/api/revalidate" 2>/dev/null; then
    ok "dashboard page rebuilt"
  else
    echo "        (could not reach Homepage to rebuild its page; it refreshes by itself within the hour)"
  fi
}
